// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID               int32      `json:"id"`
	UserID           *int32     `json:"user_id"`
	Url              *string    `json:"url"`
	IsRead           *bool      `json:"is_read"`
	TextContent      *string    `json:"text_content"`
	Summary          *string    `json:"summary"`
	Type             *string    `json:"type"`
	Tags             []string   `json:"tags"`
	Platform         *string    `json:"platform"`
	Authors          []string   `json:"authors"`
	CreatedAt        *time.Time `json:"created_at"`
	ModifiedAt       *time.Time `json:"modified_at"`
	Title            string     `json:"title"`
	ProcessingStatus *string    `json:"processing_status"`
	ProcessingError  *string    `json:"processing_error"`
}

type Podcast struct {
	ID              int32            `json:"id"`
	UserID          *int32           `json:"user_id"`
	Title           string           `json:"title"`
	Description     *string          `json:"description"`
	Status          string           `json:"status"`
	AudioUrl        *string          `json:"audio_url"`
	Dialogues       []byte           `json:"dialogues"`
	DurationSeconds *int32           `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	CompletedAt     pgtype.Timestamp `json:"completed_at"`
}

type PodcastItem struct {
	ID        int32            `json:"id"`
	PodcastID *int32           `json:"podcast_id"`
	ItemID    *int32           `json:"item_id"`
	ItemOrder int32            `json:"item_order"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           int32      `json:"id"`
	Name         *string    `json:"name"`
	Email        *string    `json:"email"`
	AuthProvider *string    `json:"auth_provider"`
	OauthID      *string    `json:"oauth_id"`
	PasswordHash *string    `json:"password_hash"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}
