// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Item struct {
	ID          int32      `json:"id"`
	UserID      *int32     `json:"user_id"`
	Url         *string    `json:"url"`
	IsRead      *bool      `json:"is_read"`
	TextContent *string    `json:"text_content"`
	Summary     *string    `json:"summary"`
	Type        *string    `json:"type"`
	Tags        []string   `json:"tags"`
	Platform    *string    `json:"platform"`
	Authors     []string   `json:"authors"`
	CreatedAt   *time.Time `json:"created_at"`
	ModifiedAt  *time.Time `json:"modified_at"`
	Title       string     `json:"title"`
}

type User struct {
	ID           int32      `json:"id"`
	Name         *string    `json:"name"`
	Email        *string    `json:"email"`
	AuthProvider *string    `json:"auth_provider"`
	OauthID      *string    `json:"oauth_id"`
	PasswordHash *string    `json:"password_hash"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}
