// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Author struct {
	ID        int32      `json:"id"`
	UserID    *int32     `json:"user_id"`
	Title     *string    `json:"title"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type Item struct {
	ID          int32      `json:"id"`
	UserID      *int32     `json:"user_id"`
	Url         *string    `json:"url"`
	IsRead      *bool      `json:"is_read"`
	FileKey     *string    `json:"file_key"`
	TextContent *string    `json:"text_content"`
	Summary     *string    `json:"summary"`
	CreatedAt   *time.Time `json:"created_at"`
	ModifiedAt  *time.Time `json:"modified_at"`
}

type ItemAuthor struct {
	ItemID   int32 `json:"item_id"`
	AuthorID int32 `json:"author_id"`
}

type ItemItemType struct {
	ItemID     int32 `json:"item_id"`
	ItemTypeID int32 `json:"item_type_id"`
}

type ItemPlatform struct {
	ItemID     int32 `json:"item_id"`
	PlatformID int32 `json:"platform_id"`
}

type ItemTag struct {
	ItemID int32 `json:"item_id"`
	TagID  int32 `json:"tag_id"`
}

type ItemType struct {
	ID        int32      `json:"id"`
	UserID    *int32     `json:"user_id"`
	Title     *string    `json:"title"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type Platform struct {
	ID        int32      `json:"id"`
	UserID    *int32     `json:"user_id"`
	Title     *string    `json:"title"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type Tag struct {
	ID        int32      `json:"id"`
	UserID    *int32     `json:"user_id"`
	Title     *string    `json:"title"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type User struct {
	ID           int32      `json:"id"`
	Name         *string    `json:"name"`
	Email        *string    `json:"email"`
	AuthProvider *string    `json:"auth_provider"`
	OauthID      *string    `json:"oauth_id"`
	PasswordHash *string    `json:"password_hash"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}
